package oletext

import "testing"

// docx tests. The body, comment, shape and document-property cases run
// against the real testdata/sample.docx (generated by testdata/gen.py); the
// chart and SmartArt cases use small in-memory packages because the Python
// generators cannot easily author those parts.

func TestDocxBody(t *testing.T) {
	extractFileWant(t, "testdata/sample.docx",
		"Report Title",
		"First body paragraph with plain text.",
		"日本語の段落テキスト。",
		"CellA",
		"CellB",
	)
}

func TestDocxComment(t *testing.T) {
	extractFileWant(t, "testdata/sample.docx",
		"This sentence is annotated.",
		"A reviewer comment.",
	)
}

func TestDocxShape(t *testing.T) {
	extractFileWant(t, "testdata/sample.docx", "Text inside a shape.")
}

func TestDocxProperties(t *testing.T) {
	extractFileWant(t, "testdata/sample.docx",
		"Doc Property Title",
		"Doc Author",
		"alpha beta",
	)
}

// TestDocxChart covers chart title/label text (DrawingML <a:t> inside a
// chart part).
func TestDocxChart(t *testing.T) {
	doc := `<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Body text</w:t></w:r></w:p></w:body></w:document>`
	chart := `<?xml version="1.0"?><c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><c:title><c:tx><c:rich><a:p><a:r><a:t>Chart Title Text</a:t></a:r></a:p></c:rich></c:tx></c:title></c:chartSpace>`
	extractWant(t, zipBytes(map[string]string{
		"word/document.xml":      doc,
		"word/charts/chart1.xml": chart,
	}), "Body text", "Chart Title Text")
}

// TestDocxSmartArt covers SmartArt diagram node text.
func TestDocxSmartArt(t *testing.T) {
	doc := `<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Body text</w:t></w:r></w:p></w:body></w:document>`
	diagram := `<?xml version="1.0"?><dgm:dataModel xmlns:dgm="http://schemas.openxmlformats.org/drawingml/2006/diagram" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><dgm:ptLst><dgm:pt><dgm:t><a:p><a:r><a:t>SmartArt Node</a:t></a:r></a:p></dgm:t></dgm:pt></dgm:ptLst></dgm:dataModel>`
	extractWant(t, zipBytes(map[string]string{
		"word/document.xml":       doc,
		"word/diagrams/data1.xml": diagram,
	}), "Body text", "SmartArt Node")
}
